### ISSUE TITLE
prone to server disconnects

### ISSUE THREAD

**Issue by mbmilligan** [ryanlovett/nbnovnc#1]
Not sure yet if this is an issue with the proxy, the choice of packages, or...

After I start the VNC session, I am usually kicked out pretty quickly with the message:

>   Server disconnected (code: 1005)

Right-clicking on the desktop is a pretty reliable way (maybe 30% chance each time) to prompt the disconnect, although other actions may trigger it too. This does not happen when I use the notebook that starts the session by hand as here: https://mybinder.org/v2/gh/ryanlovett/binder-novnc/master?filepath=start_vnc.ipynb

**Comment by ryanlovett** [comment]
Thanks! During development I too got disconnects, but they were on binder when I let the nbnovnc tabs go idle and I thought they could be caused by network timeouts, or some such. It sounds like there could be other causes too.

In your case, the disconnects did not happen with binder but did happen locally? If so could you share your notebook logs?

Were you able to invoke the menu item and reconnect to the existing VNC session?

**Comment by mbmilligan** [comment]
So far I've only tested using Binder, both with this repo and the binder-novnc demo. The issue may have been Binder connectivity after all, because the code doesn't appear to have changed but this morning I am not seeing the same crashes. As soon as I get a chance, I'll try installing locally so I can capture more logs.

Yes, reconnecting through the menu item usually works (once or twice it failed with the same disconnect message).

**Comment by ryanlovett** [comment]
I think we're running into a timeout on the websocket. Either binder could increase a read timeout, or preferably we can enable ping/pong at some configurable interval.

**Comment by ryanlovett** [comment]
Just an observation: With google-chrome open in an nbnovnc session, there was no timeout. I noticed that an I-beam cursor was blinking in the URL bar so I closed the window. Shortly after, novnc did timeout.

**Comment by ryanlovett** [comment]
Another: there was a disconnect when I had one idle terminal window open, but no disconnect when that terminal was running `top`, updating the display.

**Comment by ryanlovett** [comment]
On a JupyterHub fronted by nginx, setting:
```
    # VNC connection timeout
    proxy_read_timeout 61s;

    # Disable cache
    proxy_buffering off;
```
as [documented by novnc](https://github.com/novnc/noVNC/wiki/Proxying-with-nginx) prevents timeouts, even with no clock displayed within the desktop.

However, I still think it'd be useful to use WebSocket pings to prevent timeouts.

**Comment by ryanlovett** [comment]
Even with the above, when there are no X clients running novnc will still timeout.

**Comment by ryanlovett** [comment]
I've added support for proxying server websocket pings. This now enables nbnovnc to not disconnect for me on a JupyterHub with an nginx proxy. Something broke wrt/ binder however. Still investigating. For now I've specified a working commit on the binder launch button in the README.

**Comment by ryanlovett** [comment]
Still haven't figured out this issue that only appears on binder. The first problem is that the new pingable ws client connection can't establish a websocket (there's no "Websocket connection established" message). The second problem is the odd error below about positional arguments.

@mbmilligan Can you reproduce in your environment with nbnovnc master and nbserverproxy==0.8.0? I'm interested in whether you still get disconnects or if nbnovnc is broken for you in the same manner as on binder.

notebook log from the terminal:
> jovyan@jupyter-ryanlovett-2dnbnovnc-2dh5mzvm7s:~$ cat /proc/1/fd/2
> [I 21:59:06.727 NotebookApp] New terminal with automatic name: 2
> TermSocket.open: 2
> TermSocket.open: Opened 2
> [I 21:59:24.257 NotebookApp] Client sent subprotocols: ['binary', 'base64']
> [I 21:59:24.258 NotebookApp] Trying to establish websocket connection to ws://127.0.0.1:46627/websockify
> [I 22:10:04.083 NotebookApp] Trying to establish websocket connection to ws://127.0.0.1:46627/websockify
> [E 22:10:04.083 NotebookApp] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f554feda950>, <tornado.concurrent.Future object at 0x7f554ff5c7f0>)
>     Traceback (most recent call last):
>       File "/srv/venv/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>         ret = callback()
>       File "/srv/venv/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>         return fn(*args, **kwargs)
>       File "/srv/venv/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>         future.result()
>       File "/srv/venv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>         raise_exc_info(self._exc_info)
>       File "<string>", line 4, in raise_exc_info
>       File "/srv/venv/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
>         yielded = next(result)
>       File "<string>", line 6, in _wrap_awaitable
>       File "/srv/venv/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 153, in start_websocket_connection
>         on_message_callback=message_cb, on_ping_callback=ping_cb)
>       File "/srv/venv/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 66, in pingable_ws_connect
>         max_message_size=max_message_size)
>       File "/srv/venv/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 39, in __init__
>         max_message_size=max_message_size)
>     TypeError: __init__() missing 1 required positional argument: 'request'
>

**Comment by ryanlovett** [comment]
Fixed the kwargs problem in nbserverproxy which was due to differences between tornado 4.5.x and 5.

There's still a websocket connection issue.

**Comment by ryanlovett** [comment]
The websocket problem goes away with tornado >= 5 so I've set that as a dependency and as a requirement for binder.

So with nbserverproxy 0.8.1 and nbnovnc 0.1.1 there are no more disconnects due to proxy timeouts.
